apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgBTUQIW3YdzLxnotBhHJiUdJ9A8Mv9RDHBkzFe4Ce1gzE+FYhxzMN6fDA/JVGIPI0egvqkL9tnCdeLYaPvIySKVWaBWKawATJraoNwwcH3QUVZ3eMj9S6ipboyWZmPIUByi9O6UmlflVVHUygExOeylsPb0eV9wAqDbIOrvsgHAYi+xu7yUkU4t/FfXXDD+DuDzeYlMikqdM1mm+fdIWWcVLtJp+jfYjaDDB60ep1ited/1RvHhgONDa7rxiX8JaxpiYGzI4iM33Q9mzxxFbLexWrgi/0GQSM/iH0C4S4Ns4Eg0siECJwgOVYHkP91xR1XnT9l23k2ORcwhdSYDZjBxE0xacU/ETBmCj3dkulsIhtuoSIIV8vR7xS5Ohygf1gbyzQ7po3oEbsgTS6nxDq2X5mdw+pRHOHaO1Q4dVUzUDlYBz19xotEx9ILeg2mqcA0UqHGPLdNVtmRF3tRqeLijM8ZNeQR1yF2n/MS8EL+UBR831COZ+wUbnd37Mr5i0jiwZJ0I7aQRJamIAFf6rvah1fYfDRNQmCy3Tvxhn9hOdfmjg7JCEijl6ppZ9DKkvMGrTCg5XRzWsPqqEJR+oVq+lomEytH7b1pnDoQhDxBZ85DbJ2PfuQVNUZhLzGiW9wPVqLKTz55AFys+3U6ixlRqeFGNfgW9PsKL+1v4ojejft7ERGkHX+XjTUtfbJ8SqXVEwRoQCQ==
    user: AgAFWCpW69x7pI1YW0c4++8Mw6HyYGhiiYNY0631qDa5fMzDU2QTmBWzDgP41Jo84YFwuNTbdkS7OpV3GZosdOvzrtXtIETosT+/Ekt61HgnuIzj1kaGaNwzIQtFlY6b9FTXGZJNpJ1kPsN6bTAYJtGTITRwm09dObqgXP9yW5QBKqYuj7DAfXhtN12K1vVmndCvMQHLoqweGfRcm6Qwi3lV5t12E5x76YVRhYGtGRLkUf13TXw0qL5jiOp3hHqVQWYVXBgV7aVQFo4vnvkghLhbNXfuwsDz+HDxoWjrcAFG3NFGOaPg/yMZffx7ccdu9ov+Bkxn5OYe2TSzNCD2otF9VHR6bZ4rAb+E1sLX+5VX+hXutsJlQWiewWb4WLKxEJKTrRfyCDkyX3jDbS6W/MJ+FAAQ7gw9NIWEzuFZK78SFsqmsUlt8jifQoCYI7/f41/HzdBCmVn7//AYUwcwgJMY6yd8j0yH26T5p5raU90ZpFIq1vX8eN2Ce7Pp05YeNSvzZlYqCa2g2oYVjxFIl60i7eXpsBa/lK4ipzlENBNcw0OTr7e1GdIkqJY+jPnyVdI6SwCoyrp9YHxgfaTU+ksDIuYW4HyYvRlP1XFUis2vMqoguOQiSo2f3le0dirCxn3ywKnC8SZbPAq5dj1Sg95VyMkKaibdLpLlD17xJXPkQiZJ+fEbI9Pcy+QOSEh+EJBjwJzsnA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev
status: {}
